name: Android CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Find Project Directory and Build APK
      run: |
        # Автоматически находим, в какой папке лежит build.gradle или build.gradle.kts
        GRADLE_DIR=$(find . -name "build.gradle*" -not -path "*/build/*" | head -n 1 | xargs dirname)
        echo "Проект найден в папке: $GRADLE_DIR"
        cd "$GRADLE_DIR"
        
        # Генерируем локальный wrapper для сборки
        gradle wrapper --gradle-version 8.2
        chmod +x gradlew
        
        # Запускаем сборку приложения
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-app-apk
        path: "**/build/outputs/apk/debug/*.apk"
        
